### PR TITLE
conditional

### PR DESCRIPTION
**Pull request by Lukong123**
`N = int(input().strip())
for i in range(2, 6):
    if (N%2 == 0):
        print('Not Weird')`
please when I run this code it returns
`Not Weird
 Not Weird
 Not Weird
 Not Weird` 
if i put N as 24.
This is strange to me because I thought the for loop handled the range between 2 to 6 only.
@andrew21-mch @godsakani @Jardon237 @mbangsemarcel  please I need your help.

### CODE REVIEW

**Comment by Lukong123** [comment]
@andrew21-mch I guess I have a problem when it comes to hackerank test cases which require input from the user. I think that's what is costing me to fail all their test cases for day2

**Comment by Jardon237** [comment]
@Lukong123  i haven't had a task on loops yet

**Comment by Jardon237** [comment]
i lost track of my progress. but seems i have solve your problem @Lukong123 check my solution in the python directory

**Comment by Lukong123** [comment]
> i lost track of my progress. but seems i have solve your problem @Lukong123 check my solution in the python directory

okay thanks.

**Pull request merged**
